const tags = {
  auth: "Authorization",
  order: "Order",
  settings: "Settings",
  music: "Music",
  whatsapp: "Whatsapp",
  features: "Features",
  brideGroom: "Bride Groom",
  events: "Events",
  testimonial: "Testimonial",
  stories: "Stories",
  gallery: "Gallery",
  video: "Video",
  map: "Map",
  themes: "Themes",
  categories: "Categories",
  subCategories: "Sub Categories",
  orders: "Orders",
  socialMedia: "Social Media",
  rekening: "Rekening",
  payments: "Payments",
  setting: "Setting",
  articles: "Articles",
  faq: "faq",
};

export default tags;
