import "@public/css/MuiStyling.css";
import "@public/css/globals.css";
import "@public/css/preflight.css";

import { Rubik } from "next/font/google";

import { Provider } from "./provider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html>
      <body className={`${rubik.className}`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};

export default RootLayout;
