import { Rubik } from "next/font/google";
import "./globals.css";
import { Provider } from "./provider";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html>
      <body className={`${rubik.className} bg-slate-200`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
};

export default RootLayout;
